// ====== HIFZ DEPARTMENT MODULE ======
const JUZ_NAMES=['الم','سیقول','تلک الرسل','لن تنالوا','والمحصنات','لایحب اللہ','واذا سمعوا','ولو اننا','قال الملأ','واعلموا','یعتذرون','وما من دابۃ','وما ابرئ','ربما','سبحان الذی','قال الم','اقترب','قد افلح','وقال الذین','امن خلق','اتل ما اوحی','ومن یقنت','وما لی','فمن اظلم','الیہ یرد','حم','قال فما خطبکم','قد سمع اللہ','تبارک الذی','عم'];
const SURAH_DATA=[{n:'الفاتحہ',j:1},{n:'البقرہ',j:1},{n:'آل عمران',j:3},{n:'النساء',j:4},{n:'المائدہ',j:6},{n:'الانعام',j:7},{n:'الاعراف',j:8},{n:'الانفال',j:9},{n:'التوبہ',j:10},{n:'یونس',j:11},{n:'ھود',j:11},{n:'یوسف',j:12},{n:'الرعد',j:13},{n:'ابراھیم',j:13},{n:'الحجر',j:14},{n:'النحل',j:14},{n:'بنی اسرائیل',j:15},{n:'الکھف',j:15},{n:'مریم',j:16},{n:'طٰہٰ',j:16},{n:'الانبیاء',j:17},{n:'الحج',j:17},{n:'المؤمنون',j:18},{n:'النور',j:18},{n:'الفرقان',j:18},{n:'الشعراء',j:19},{n:'النمل',j:19},{n:'القصص',j:20},{n:'العنکبوت',j:20},{n:'الروم',j:21},{n:'لقمان',j:21},{n:'السجدہ',j:21},{n:'الاحزاب',j:21},{n:'سبا',j:22},{n:'فاطر',j:22},{n:'یٰسٓ',j:22},{n:'الصافات',j:23},{n:'ص',j:23},{n:'الزمر',j:23},{n:'غافر',j:24},{n:'فصلت',j:24},{n:'الشوریٰ',j:25},{n:'الزخرف',j:25},{n:'الدخان',j:25},{n:'الجاثیہ',j:25},{n:'الاحقاف',j:26},{n:'محمد',j:26},{n:'الفتح',j:26},{n:'الحجرات',j:26},{n:'ق',j:26},{n:'الذاریات',j:26},{n:'الطور',j:27},{n:'النجم',j:27},{n:'القمر',j:27},{n:'الرحمٰن',j:27},{n:'الواقعہ',j:27},{n:'الحدید',j:27},{n:'المجادلہ',j:28},{n:'الحشر',j:28},{n:'الممتحنہ',j:28},{n:'الصف',j:28},{n:'الجمعہ',j:28},{n:'المنافقون',j:28},{n:'التغابن',j:28},{n:'الطلاق',j:28},{n:'التحریم',j:28},{n:'الملک',j:29},{n:'القلم',j:29},{n:'الحاقہ',j:29},{n:'المعارج',j:29},{n:'نوح',j:29},{n:'الجن',j:29},{n:'المزمل',j:29},{n:'المدثر',j:29},{n:'القیامۃ',j:29},{n:'الدھر',j:29},{n:'المرسلات',j:29},{n:'النبا',j:30},{n:'النازعات',j:30},{n:'عبس',j:30},{n:'التکویر',j:30},{n:'الانفطار',j:30},{n:'المطففین',j:30},{n:'الانشقاق',j:30},{n:'البروج',j:30},{n:'الطارق',j:30},{n:'الاعلیٰ',j:30},{n:'الغاشیہ',j:30},{n:'الفجر',j:30},{n:'البلد',j:30},{n:'الشمس',j:30},{n:'اللیل',j:30},{n:'الضحیٰ',j:30},{n:'الم نشرح',j:30},{n:'التین',j:30},{n:'العلق',j:30},{n:'القدر',j:30},{n:'البینہ',j:30},{n:'الزلزال',j:30},{n:'العادیات',j:30},{n:'القارعہ',j:30},{n:'التکاثر',j:30},{n:'العصر',j:30},{n:'الھمزہ',j:30},{n:'الفیل',j:30},{n:'قریش',j:30},{n:'الماعون',j:30},{n:'الکوثر',j:30},{n:'الکافرون',j:30},{n:'النصر',j:30},{n:'اللھب',j:30},{n:'الاخلاص',j:30},{n:'الفلق',j:30},{n:'الناس',j:30}];
let hifzTrackingMode='juz';
function qualityClass(q){if(q==='ممتاز')return'excellent';if(q==='جید'||q==='جید جداً')return'good';if(q==='متوسط')return'average';return'weak';}
function statusLabel(s){const m={active:'<span class="badge-green">فعال</span>',completed:'<span class="badge-gold">تکمیل</span>',paused:'<span class="badge-blue">رُکا ہوا</span>',withdrawn:'<span class="badge-red">دستبردار</span>'};return m[s]||s;}
function switchHifzTab(tab){document.querySelectorAll('[id^="hifzTab-"]').forEach(d=>d.style.display='none');const t=document.getElementById('hifzTab-'+tab);if(t)t.style.display='block';document.querySelectorAll('#hifzTabs button').forEach(b=>b.classList.remove('active'));event.target.closest('button').classList.add('active');if(tab==='progress')loadHifzProgressTable();if(tab==='juzgrid')loadJuzGrid();if(tab==='evaluations')loadHifzEvaluationsTable();}
function setHifzTrackingMode(mode){hifzTrackingMode=mode;document.querySelectorAll('#hifzTrackingMode button').forEach(b=>{b.classList.toggle('active',b.textContent.includes(mode==='juz'?'پارہ':'سورہ'));});loadJuzGrid();}
async function getHifzStats(){const[hs,hp]=await Promise.all([dbGetAll('hifzStudents'),dbGetAll('hifzProgress')]);const active=hs.filter(h=>h.status==='active').length;const completed=hs.filter(h=>h.status==='completed').length;const totalJuz=hs.reduce((a,h)=>(h.completedJuz||[]).length+a,0);const avg=hs.length?Math.round(totalJuz/hs.length*10)/10:0;const thisMonth=today().substring(0,7);const monthCompleted=hs.filter(h=>h.status==='completed'&&h.completionDate&&h.completionDate.startsWith(thisMonth)).length;return{active,completed,avg,monthCompleted,totalStudents:hs.length};}
async function renderHifzStats(){const s=await getHifzStats();const el=document.getElementById('hifzStatCards');if(!el)return;el.innerHTML=`<div class="hifz-stat"><div class="stat-num">${s.active}</div><div class="stat-label">فعال حفاظ</div></div><div class="hifz-stat"><div class="stat-num">${s.completed}</div><div class="stat-label">تکمیل شدہ</div></div><div class="hifz-stat"><div class="stat-num">${s.avg}</div><div class="stat-label">اوسط پارے</div></div><div class="hifz-stat"><div class="stat-num">${s.monthCompleted}</div><div class="stat-label">اس ماہ تکمیل</div></div>`;}
async function populateHifzSelects(){const[hs,students,teachers]=await Promise.all([dbGetAll('hifzStudents'),dbGetAll('students'),dbGetAll('teachers')]);const activeHs=hs.filter(h=>h.status==='active'||h.status==='paused');const selIds=['hifzProgressStudent','hifzJuzStudent','hifzEvalStudent'];selIds.forEach(id=>{const sel=document.getElementById(id);if(!sel)return;const first=sel.options[0]?sel.options[0].textContent:'';sel.innerHTML='<option value="">'+first+'</option>';activeHs.forEach(h=>{const st=students.find(s=>s.id===h.studentId);if(st){const o=document.createElement('option');o.value=h.id;o.textContent=st.name;sel.appendChild(o);}});});}
async function loadHifzPage(){await renderHifzStats();await populateHifzSelects();await loadHifzStudentsTable();}
