// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": ".gitignore",
        "revision": "0ad8281b52754ab07f41b3b836234ab4"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.pyw",
        "revision": "d3ceb161cfab9e9c5f40a93e15e5be27"
    },
    {
        "url": "client readme Guide D.md",
        "revision": "96f7c54b97e5a4accbec951c275ba392"
    },
    {
        "url": "client readme Guide Q.md",
        "revision": "de3484224348da2e2436daddb82b8296"
    },
    {
        "url": "features and functionalities.md",
        "revision": "ad7f8b837ae43ed75c6a4de23ee83b7c"
    },
    {
        "url": "features and functionalities2.md",
        "revision": "3cb9ef8a58e89060a37190b57da19c00"
    },
    {
        "url": "hifz.js",
        "revision": "2c99dc26232a0917563d5bc7a9e489a5"
    },
    {
        "url": "hifz2.js",
        "revision": "57e1fabc84fe8bfa5554f0a1b8f1a9c3"
    },
    {
        "url": "hifz3.js",
        "revision": "6747e43a2ba4e264fe72639383a67b02"
    },
    {
        "url": "index Version 2.html",
        "revision": "1fdbb8c1f9770adbf05cdaa1876ac02e"
    },
    {
        "url": "index.html",
        "revision": "92c6aa36b55fe807a564696216ef8547"
    },
    {
        "url": "index2_enhanced_full.html",
        "revision": "6fb66dfdf4fb00cc7a98f1a77e031f3e"
    },
    {
        "url": "Madrasa management app apk installer.apk",
        "revision": "6483158731520b97a2ae7518a819889d"
    },
    {
        "url": "madrasa_management_indexeddb.html",
        "revision": "3438e01072068b9e6fae1edf8a0b853a"
    },
    {
        "url": "manifest.json",
        "revision": "8c8790cc26edba6e2e0dd6719861eb9a"
    },
    {
        "url": "offline.html",
        "revision": "ad17d01f02bb01615fbc0509f5aee82a"
    },
    {
        "url": "pwa-register.js",
        "revision": "3ec872e4f752840ad8f85922ff6cebe7"
    },
    {
        "url": "readme.md",
        "revision": "0f287a209ca30758f00afb386eadf286"
    },
    {
        "url": "readmeD.md",
        "revision": "3e1692122e3b43cc771541487c0f5b18"
    },
    {
        "url": "sw.js",
        "revision": "6b8fb34d74138ce7701c08276ed741bf"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}